import Link from "next/link";

export default function EditorialGuidePage() {
  return (
    <main className="min-h-screen bg-stone-50">
      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <header className="border-b-2 border-stone-800 pb-6 mb-8">
          <Link href="/" className="text-xs font-medium tracking-widest uppercase text-stone-400 hover:text-stone-700 transition-colors">
            ← Morning Edition
          </Link>
          <h1 className="font-serif text-4xl font-bold text-stone-900 mt-3">Editorial Standards</h1>
          <p className="text-sm text-stone-500 mt-1">
            How Morning Edition decides what to publish and why.
          </p>
        </header>

        <div className="prose prose-stone max-w-none space-y-8 text-sm leading-relaxed text-stone-700">
          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">The purpose</h2>
            <p>
              Morning Edition is not a news aggregator. It is a shared front page — a finite,
              daily object designed to give people enough shared context to participate in their
              community. It is not trying to keep you on the site. It is trying to get you off
              it and into the world.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">What we select</h2>
            <p>
              We look for stories and events that are useful to know, locally grounded, and worth
              talking about. We prefer things that give readers shared context — not things that
              confirm existing views or provoke emotional reactions.
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Does this help someone participate in their community?</li>
              <li>Is this genuinely useful to know today?</li>
              <li>Would most reasonable people want to know this?</li>
              <li>Can we source it?</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">What we avoid</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Clickbait headlines or misleading framing</li>
              <li>Partisan language or editorial spin without disclosure</li>
              <li>Claims without source links</li>
              <li>Stories selected for emotional engagement rather than informational value</li>
              <li>Conflict for its own sake</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">On AI involvement</h2>
            <p>
              AI tools help us gather, summarize, and draft candidate content. Every piece of content
              includes a provenance label:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>
                <strong>AI drafted</strong> — generated by AI, not yet reviewed by a human editor.
                This content should not be published as-is.
              </li>
              <li>
                <strong>AI drafted · Human approved</strong> — AI-generated, reviewed and approved
                by an editor. This is the minimum standard for publication.
              </li>
              <li>
                <strong>Human written</strong> — written entirely by a human editor.
              </li>
              <li>
                <strong>Community submitted</strong> — sourced from community input and reviewed
                before publication.
              </li>
            </ul>
            <p className="mt-2">
              The editor is responsible for everything that is published. AI does not publish
              directly. There is always a human in the loop before anything goes live.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">On neutrality</h2>
            <p>
              We do not pretend to be neutral. We have editorial values: we believe in source
              transparency, in giving readers context rather than conclusions, and in the
              importance of shared local knowledge. We will make these choices visible rather than
              pretending they don&apos;t exist.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-bold text-stone-900 mb-2">The editor&apos;s responsibility</h2>
            <p>
              The editor — a human being — is responsible for the final content of every edition.
              If something is wrong, incomplete, or harmful, that is on the editor. Use the
              provenance system honestly. Don&apos;t publish things you haven&apos;t read. Don&apos;t approve
              things you can&apos;t verify.
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-stone-200">
          <Link
            href="/"
            className="text-xs font-medium tracking-widest uppercase text-stone-400 hover:text-stone-700 transition-colors"
          >
            ← Back to today&apos;s edition
          </Link>
        </div>
      </div>
    </main>
  );
}
